### ISSUE TITLE
Unable to import custom post type and taxonomy

### ISSUE THREAD

**Issue by theemwiz** [wpmetabox/mb-custom-post-type#13]
I created a custom post type named "Portfolio" with slug "portfolio-wp" and taxonomy named "Category" with slug "portfolio-category" on my local site. I exported the XML and then tried to import on a live server with fresh WordPress install. But, there it is showing invalid post type for both custom post type and taxonomy.

Can you let me know how to resolve this issue?

**Comment by rilwis** [comment]
Did you install and activate the plugin on your live site?
