### ISSUE TITLE
Undefined index 'meta_box_cb' in taxonomy/register.php

### ISSUE THREAD

**Issue by eyesofjeremy** [wpmetabox/mb-custom-post-type#18]
Hi there,

This recently cropped up in development — I was getting this notice:

` Notice: Undefined index: meta_box_cb in /Users/jeremy/www/sites/gtt/-www-/site-content/plugins/meta-box-aio/vendor/meta-box/mb-custom-post-type/inc/taxonomy/register.php on line 83`

I saw this with the newest version of WordPress (5.2.3), Twentynineteen theme, no plugins active besides Metabox and Metabox All-In-One.

Replacing this on line 83:

    if ( false !== $args['meta_box_cb'] ) {

with this:

    if ( isset( $args['meta_box_cb'] ) && false !== $args['meta_box_cb'] ) {

... fixed my issue. Happy to submit a pull request if that's helpful.

Thanks,
Jeremy

**Comment by rilwis** [comment]
Hi Jeremy, thanks a lot for your feedback. It's very helpful. Please submit a PR, so I can add the credit to you!

**Comment by eyesofjeremy** [comment]
I think that should cover it, but let me know if not.

Best,
J

**Comment by rilwis** [comment]
Thanks a lot for your help. I've just merged it!
