### ISSUE TITLE
Critical error on update to version 2.3.0

### ISSUE THREAD

**Issue by djalondon** [wpmetabox/mb-custom-post-type#42]
When seeking help with this issue, you may be asked for some of the following information:
WordPress version 5.8.2
Current theme: Oshin Child (version 6.5.1536925382)
Current plugin: MB Custom Post Types & Custom Taxonomies (version 2.3.0)
PHP version 7.4.26

Error Details
=============
An error of type E_ERROR was caused in line 29 of the file /var/www/vhosts/{ website }/httpdocs/wp-content/plugins/mb-custom-post-type/mb-custom-post-type.php. Error message: Uncaught Error: Class 'MBCPT\PostTypeRegister' not found in /var/www/vhosts/{ website }/httpdocs/wp-content/plugins/mb-custom-post-type/mb-custom-post-type.php:29
Stack trace:
#0 /var/www/vhosts/{ website }/httpdocs/wp/wp-includes/class-wp-hook.php(303): mb_cpt_load()
#1 /var/www/vhosts/{ website }/httpdocs/wp/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters()
#2 /var/www/vhosts/{ website }/httpdocs/wp/wp-includes/plugin.php(470): WP_Hook->do_action()
#3 /var/www/vhosts/{ website }/httpdocs/wp/wp-settings.php(578): do_action()
#4 /var/www/vhosts/{ website }/httpdocs/wp/wp-config.php(131): require_once('/var/www/vhosts...')
#5 /var/www/vhosts/{ website }/httpdocs/wp/wp-load.php(50): require_once('/var/www/vhosts...')
#6 /var/www/vhosts/{ website }/httpdocs/wp/wp-login.php(12): require('/var/www/vhosts...')
#7 {main}
thrown

**Comment by rilwis** [comment]
Thanks a lot for your feedback. The CI/CD to deploy to WordPress.org had a problem. We have fixed it. Please remove the plugin and re-install it.

**Comment by djalondon** [comment]
When you say "remove" do you mean delete the files?

**Comment by djalondon** [comment]
Thanks, this is working again now
