### ISSUE TITLE
Handle rewrite correctly

### ISSUE THREAD

**Issue by skynet** [wpmetabox/mb-custom-post-type#8]
Is this able to handle rewriting correctly?

Working only for the first level: `/post_type/child`

Doesn't work: `/post_type/child/grandchild`

**Comment by truongwp** [comment]
Hi @skynet,
I tested but it works correctly. Can you test again?

**Comment by rilwis** [comment]
After checking this issue, I see it's still working. Note that you need to set the `hierarchical` param to `true` to make it works.
